/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/federations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all federations */
        get: operations["federations.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/federations/{federation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show one federation */
        get: operations["federations.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all seasons */
        get: operations["seasons.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show one season */
        get: operations["seasons.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member-organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all member-organizations */
        get: operations["member-organizations.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member-organizations/{member_organization}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show one member-organization */
        get: operations["member-organizations.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all registration-windows */
        get: operations["registration-windows.index"];
        put?: never;
        /** Store one registration-window */
        post: operations["registration-windows.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-windows/{registration_window}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show one registration-window */
        get: operations["registration-windows.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update one registration-window */
        patch: operations["registration-windows.update"];
        trace?: never;
    };
    "/registration-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all registration-applications */
        get: operations["registration-applications.index"];
        put?: never;
        /** Store one registration-application */
        post: operations["registration-applications.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show one registration-application */
        get: operations["registration-applications.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update one registration-application */
        patch: operations["registration-applications.update"];
        trace?: never;
    };
    "/application-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all application-documents */
        get: operations["application-documents.index"];
        put?: never;
        /** Store one application-document */
        post: operations["application-documents.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/application-documents/{application_document}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show one application-document */
        get: operations["application-documents.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update one application-document */
        patch: operations["application-documents.update"];
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a draft or resubmit after an information request (applicant). */
        post: operations["registration-applications.Submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an open application (applicant). */
        post: operations["registration-applications.Cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/start-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a submitted application under review (reviewer). */
        post: operations["registration-applications.StartReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/request-information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send the application back to the applicant with a reason (reviewer). */
        post: operations["registration-applications.RequestInformation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve an application under review (reviewer). */
        post: operations["registration-applications.Approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject an application under review with a reason (reviewer). */
        post: operations["registration-applications.Reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration-applications/{registration_application}/-actions/refresh-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the Learning Center for the applicant's current credentials and store the snapshot (reviewer, approved applications). 503 when the Learning Center is unavailable. */
        post: operations["registration-applications.RefreshCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Helper/Errors */
        "helper.errors": {
            detail?: string;
            status: string;
            title: string;
            source?: {
                pointer?: string;
            };
        }[];
        /** Helper/JSONAPI */
        "helper.jsonapi": {
            /**
             * version
             * @example 1.0
             */
            version: string;
        };
        /** Resource/Application-document/Fetch */
        "resources.application-documents.resource.fetch": {
            /**
             * type
             * @default application-documents
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * documentType
                 * @example proof_of_age
                 */
                documentType?: string;
                /**
                 * fileName
                 * @example proof-of-age.pdf
                 */
                fileName?: string;
                /**
                 * mimeType
                 * @example application/pdf
                 */
                mimeType?: string;
                /**
                 * sizeBytes
                 * @example 120000
                 */
                sizeBytes?: number;
                /**
                 * checksumSha256
                 * @example 1e7bfd03f48c994eeb2a84442dffa7306effcbd0844768ff492f11285f8715c8
                 */
                checksumSha256?: string;
                /**
                 * reviewStatus
                 * @example pending
                 */
                reviewStatus?: string;
                /** reviewNote */
                reviewNote?: string;
                /** reviewedAt */
                readonly reviewedAt?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:16.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:16.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** application */
                application?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/applications/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/applications/1
                         */
                        self?: string;
                    };
                };
                /** reviewedBy */
                reviewedBy?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/reviewed-bies/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/reviewed-bies/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Application-document/Store */
        "resources.application-documents.resource.store": {
            /**
             * type
             * @default application-documents
             */
            type: string;
            attributes: {
                /**
                 * documentType
                 * @example proof_of_age
                 */
                documentType?: string;
                /**
                 * fileName
                 * @example proof-of-age.pdf
                 */
                fileName?: string;
                /**
                 * mimeType
                 * @example application/pdf
                 */
                mimeType?: string;
                /**
                 * sizeBytes
                 * @example 120000
                 */
                sizeBytes?: number;
                /**
                 * checksumSha256
                 * @example 1e7bfd03f48c994eeb2a84442dffa7306effcbd0844768ff492f11285f8715c8
                 */
                checksumSha256?: string;
                /**
                 * reviewStatus
                 * @example pending
                 */
                reviewStatus?: string;
                /** reviewNote */
                reviewNote?: string;
                /** reviewedAt */
                readonly reviewedAt?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:16.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:16.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** application */
                application?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/applications/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/applications/1
                         */
                        self?: string;
                    };
                };
                /** reviewedBy */
                reviewedBy?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/reviewed-bies/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/reviewed-bies/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Application-document/Update */
        "resources.application-documents.resource.update": {
            /**
             * type
             * @default application-documents
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * documentType
                 * @example proof_of_age
                 */
                documentType?: string;
                /**
                 * fileName
                 * @example proof-of-age.pdf
                 */
                fileName?: string;
                /**
                 * mimeType
                 * @example application/pdf
                 */
                mimeType?: string;
                /**
                 * sizeBytes
                 * @example 120000
                 */
                sizeBytes?: number;
                /**
                 * checksumSha256
                 * @example 1e7bfd03f48c994eeb2a84442dffa7306effcbd0844768ff492f11285f8715c8
                 */
                checksumSha256?: string;
                /**
                 * reviewStatus
                 * @example pending
                 */
                reviewStatus?: string;
                /** reviewNote */
                reviewNote?: string;
                /** reviewedAt */
                readonly reviewedAt?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:16.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:16.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** application */
                application?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/applications/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/applications/1
                         */
                        self?: string;
                    };
                };
                /** reviewedBy */
                reviewedBy?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/reviewed-bies/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/reviewed-bies/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Federation/Fetch */
        "resources.federations.resource.fetch": {
            /**
             * type
             * @default federations
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * name
                 * @example Northgate Soccer Federation
                 */
                readonly name?: string;
                /**
                 * code
                 * @example NSF
                 */
                readonly code?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:14.000000Z
                 */
                readonly createdAt?: string;
            };
            relationships?: {
                /** seasons */
                seasons?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        self?: string;
                    };
                };
                /** memberOrganizations */
                memberOrganizations?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Member-organization/Fetch */
        "resources.member-organizations.resource.fetch": {
            /**
             * type
             * @default member-organizations
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * name
                 * @example Northgate Youth Soccer Association
                 */
                readonly name?: string;
                /**
                 * code
                 * @example NYSA
                 */
                readonly code?: string;
            };
            relationships?: {
                /** federation */
                federation?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/federations/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/federations/1
                         */
                        self?: string;
                    };
                };
                /** registrationWindows */
                registrationWindows?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/registration-windows/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/registration-windows/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Registration-application/Fetch */
        "resources.registration-applications.resource.fetch": {
            /**
             * type
             * @default registration-applications
             */
            type: string;
            /** @example 3 */
            id: string;
            attributes: {
                /**
                 * role
                 * @example referee
                 */
                role?: string;
                /**
                 * status
                 * @example approved
                 */
                readonly status?: string;
                /** statusReason */
                readonly statusReason?: string;
                /**
                 * dateOfBirth
                 * @example 1990-06-21T00:00:00.000000Z
                 */
                dateOfBirth?: string;
                /** phone */
                phone?: string;
                /** applicantNotes */
                applicantNotes?: string;
                /** missingRequiredDocuments */
                readonly missingRequiredDocuments?: unknown[];
                /**
                 * submittedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly submittedAt?: string;
                /**
                 * decidedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly decidedAt?: string;
                /** cancelledAt */
                readonly cancelledAt?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** registrationWindow */
                registrationWindow?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/registration-windows/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/registration-windows/3
                         */
                        self?: string;
                    };
                };
                /** memberOrganization */
                memberOrganization?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/3
                         */
                        self?: string;
                    };
                };
                /** season */
                season?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/3
                         */
                        self?: string;
                    };
                };
                /** applicant */
                applicant?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/applicants/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/applicants/3
                         */
                        self?: string;
                    };
                };
                /** documents */
                documents?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/documents/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/documents/3
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Registration-application/Store */
        "resources.registration-applications.resource.store": {
            /**
             * type
             * @default registration-applications
             */
            type: string;
            attributes: {
                /**
                 * role
                 * @example referee
                 */
                role?: string;
                /**
                 * status
                 * @example approved
                 */
                readonly status?: string;
                /** statusReason */
                readonly statusReason?: string;
                /**
                 * dateOfBirth
                 * @example 1990-06-21T00:00:00.000000Z
                 */
                dateOfBirth?: string;
                /** phone */
                phone?: string;
                /** applicantNotes */
                applicantNotes?: string;
                /** missingRequiredDocuments */
                readonly missingRequiredDocuments?: unknown[];
                /**
                 * submittedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly submittedAt?: string;
                /**
                 * decidedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly decidedAt?: string;
                /** cancelledAt */
                readonly cancelledAt?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** registrationWindow */
                registrationWindow?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/registration-windows/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/registration-windows/3
                         */
                        self?: string;
                    };
                };
                /** memberOrganization */
                memberOrganization?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/3
                         */
                        self?: string;
                    };
                };
                /** season */
                season?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/3
                         */
                        self?: string;
                    };
                };
                /** applicant */
                applicant?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/applicants/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/applicants/3
                         */
                        self?: string;
                    };
                };
                /** documents */
                documents?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/documents/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/documents/3
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Registration-application/Update */
        "resources.registration-applications.resource.update": {
            /**
             * type
             * @default registration-applications
             */
            type: string;
            /** @example 3 */
            id: string;
            attributes: {
                /**
                 * role
                 * @example referee
                 */
                role?: string;
                /**
                 * status
                 * @example approved
                 */
                readonly status?: string;
                /** statusReason */
                readonly statusReason?: string;
                /**
                 * dateOfBirth
                 * @example 1990-06-21T00:00:00.000000Z
                 */
                dateOfBirth?: string;
                /** phone */
                phone?: string;
                /** applicantNotes */
                applicantNotes?: string;
                /** missingRequiredDocuments */
                readonly missingRequiredDocuments?: unknown[];
                /**
                 * submittedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly submittedAt?: string;
                /**
                 * decidedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly decidedAt?: string;
                /** cancelledAt */
                readonly cancelledAt?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:17.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** registrationWindow */
                registrationWindow?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/registration-windows/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/registration-windows/3
                         */
                        self?: string;
                    };
                };
                /** memberOrganization */
                memberOrganization?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/3
                         */
                        self?: string;
                    };
                };
                /** season */
                season?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/3
                         */
                        self?: string;
                    };
                };
                /** applicant */
                applicant?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/applicants/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/applicants/3
                         */
                        self?: string;
                    };
                };
                /** documents */
                documents?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/documents/3
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/documents/3
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Registration-window/Fetch */
        "resources.registration-windows.resource.fetch": {
            /**
             * type
             * @default registration-windows
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * opensAt
                 * @example 2026-08-19T18:55:15.000000Z
                 */
                opensAt?: string;
                /**
                 * closesAt
                 * @example 2026-11-02T18:55:15.000000Z
                 */
                closesAt?: string;
                /**
                 * roles
                 * @example [
                 *       "participant",
                 *       "coach",
                 *       "referee"
                 *     ]
                 */
                roles?: unknown[];
                /** isOpen */
                readonly isOpen?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:15.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:15.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** memberOrganization */
                memberOrganization?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        self?: string;
                    };
                };
                /** season */
                season?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        self?: string;
                    };
                };
                /** createdBy */
                createdBy?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/created-bies/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/created-bies/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Registration-window/Store */
        "resources.registration-windows.resource.store": {
            /**
             * type
             * @default registration-windows
             */
            type: string;
            attributes: {
                /**
                 * opensAt
                 * @example 2026-08-19T18:55:15.000000Z
                 */
                opensAt?: string;
                /**
                 * closesAt
                 * @example 2026-11-02T18:55:15.000000Z
                 */
                closesAt?: string;
                /**
                 * roles
                 * @example [
                 *       "participant",
                 *       "coach",
                 *       "referee"
                 *     ]
                 */
                roles?: unknown[];
                /** isOpen */
                readonly isOpen?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:15.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:15.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** memberOrganization */
                memberOrganization?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        self?: string;
                    };
                };
                /** season */
                season?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        self?: string;
                    };
                };
                /** createdBy */
                createdBy?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/created-bies/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/created-bies/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Registration-window/Update */
        "resources.registration-windows.resource.update": {
            /**
             * type
             * @default registration-windows
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * opensAt
                 * @example 2026-08-19T18:55:15.000000Z
                 */
                opensAt?: string;
                /**
                 * closesAt
                 * @example 2026-11-02T18:55:15.000000Z
                 */
                closesAt?: string;
                /**
                 * roles
                 * @example [
                 *       "participant",
                 *       "coach",
                 *       "referee"
                 *     ]
                 */
                roles?: unknown[];
                /** isOpen */
                readonly isOpen?: string;
                /**
                 * createdAt
                 * @example 2026-09-02T18:55:15.000000Z
                 */
                readonly createdAt?: string;
                /**
                 * updatedAt
                 * @example 2026-09-02T18:55:15.000000Z
                 */
                readonly updatedAt?: string;
            };
            relationships?: {
                /** memberOrganization */
                memberOrganization?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/member-organizations/1
                         */
                        self?: string;
                    };
                };
                /** season */
                season?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/seasons/1
                         */
                        self?: string;
                    };
                };
                /** createdBy */
                createdBy?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/created-bies/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/created-bies/1
                         */
                        self?: string;
                    };
                };
            };
        };
        /** Resource/Season/Fetch */
        "resources.seasons.resource.fetch": {
            /**
             * type
             * @default seasons
             */
            type: string;
            /** @example 1 */
            id: string;
            attributes: {
                /**
                 * label
                 * @example 2025/26
                 */
                readonly label?: string;
                /**
                 * startsOn
                 * @example 2025-09-01T00:00:00.000000Z
                 */
                readonly startsOn?: string;
                /**
                 * endsOn
                 * @example 2026-08-31T00:00:00.000000Z
                 */
                readonly endsOn?: string;
            };
            relationships?: {
                /** federation */
                federation?: {
                    readonly links?: {
                        /**
                         * related
                         * @example http://localhost:3001/api/v1/federation/federations/1
                         */
                        related?: string;
                        /**
                         * self
                         * @example http://localhost:3001/api/v1/federation/federations/1
                         */
                        self?: string;
                    };
                };
            };
        };
    };
    responses: {
        /** @description Bad request */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/vnd.api+json": {
                    "helper.jsonapi"?: components["schemas"]["helper.jsonapi"];
                    "helper.errors"?: components["schemas"]["helper.errors"];
                };
            };
        };
        /** @description Unauthorized Action */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/vnd.api+json": {
                    "helper.jsonapi"?: components["schemas"]["helper.jsonapi"];
                    "helper.errors"?: components["schemas"]["helper.errors"];
                };
            };
        };
        /** @description Content Not Found */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/vnd.api+json": {
                    "helper.jsonapi"?: components["schemas"]["helper.jsonapi"];
                    "helper.errors"?: components["schemas"]["helper.errors"];
                };
            };
        };
        /** @description Unprocessable Entity */
        422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/vnd.api+json": {
                    "helper.jsonapi"?: components["schemas"]["helper.jsonapi"];
                    "helper.errors"?: components["schemas"]["helper.errors"];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "federations.index": {
        parameters: {
            query?: {
                sort?: ("id" | "-id")[];
                /** @description A list of ids to filter by. */
                "filter[id]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index federations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.federations.resource.fetch"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
        };
    };
    "federations.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                federation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show federations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.federations.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "seasons.index": {
        parameters: {
            query?: {
                sort?: ("id" | "-id")[];
                /** @description A list of ids to filter by. */
                "filter[id]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index seasons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.seasons.resource.fetch"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
        };
    };
    "seasons.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show seasons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.seasons.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "member-organizations.index": {
        parameters: {
            query?: {
                sort?: ("id" | "-id")[];
                /** @description A list of ids to filter by. */
                "filter[id]"?: string[];
                /** @description Filters the records */
                "filter[code]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index member-organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.member-organizations.resource.fetch"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
        };
    };
    "member-organizations.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_organization: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show member-organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.member-organizations.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-windows.index": {
        parameters: {
            query?: {
                sort?: ("id" | "-id" | "opensAt" | "-opensAt" | "closesAt" | "-closesAt")[];
                /** @description A list of ids to filter by. */
                "filter[id]"?: string[];
                /** @description Filters the records */
                "filter[memberOrganization]"?: string;
                /** @description Filters the records */
                "filter[season]"?: string;
                /** @description Filters the records */
                "filter[open]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index registration-windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-windows.resource.fetch"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
        };
    };
    "registration-windows.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    data: components["schemas"]["resources.registration-windows.resource.store"];
                };
            };
        };
        responses: {
            /** @description Store registration-windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-windows.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-windows.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_window: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show registration-windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-windows.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-windows.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_window: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    data: components["schemas"]["resources.registration-windows.resource.update"];
                };
            };
        };
        responses: {
            /** @description Update registration-windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-windows.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-applications.index": {
        parameters: {
            query?: {
                sort?: ("id" | "-id" | "submittedAt" | "-submittedAt" | "createdAt" | "-createdAt")[];
                /** @description A list of ids to filter by. */
                "filter[id]"?: string[];
                /** @description A list of statuss to filter by. */
                "filter[status]"?: string[];
                /** @description Filters the records */
                "filter[memberOrganization]"?: string;
                /** @description Filters the records */
                "filter[season]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
        };
    };
    "registration-applications.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    data: components["schemas"]["resources.registration-applications.resource.store"];
                };
            };
        };
        responses: {
            /** @description Store registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-applications.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-applications.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    data: components["schemas"]["resources.registration-applications.resource.update"];
                };
            };
        };
        responses: {
            /** @description Update registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "application-documents.index": {
        parameters: {
            query?: {
                sort?: ("id" | "-id")[];
                /** @description A list of ids to filter by. */
                "filter[id]"?: string[];
                /** @description Filters the records */
                "filter[application]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index application-documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.application-documents.resource.fetch"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
        };
    };
    "application-documents.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    data: components["schemas"]["resources.application-documents.resource.store"];
                };
            };
        };
        responses: {
            /** @description Store application-documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.application-documents.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "application-documents.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_document: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show application-documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.application-documents.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "application-documents.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_document: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    data: components["schemas"]["resources.application-documents.resource.update"];
                };
            };
        };
        responses: {
            /** @description Update application-documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.application-documents.resource.fetch"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    "registration-applications.Submit": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "registration-applications.Cancel": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "registration-applications.StartReview": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "registration-applications.RequestInformation": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "registration-applications.Approve": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "registration-applications.Reject": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "registration-applications.RefreshCredentials": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the current state instead of failing. */
                "Idempotency-Key"?: string;
                /** @description Correlation id echoed in the response and stored with the audit entry. */
                "X-Request-Id"?: string;
            };
            path: {
                registration_application: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    meta?: {
                        /** @description Required for request-information and reject. */
                        reason?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Show registration-applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        jsonapi: {
                            /**
                             * version
                             * @example 1.0
                             */
                            version?: string;
                        };
                        data: components["schemas"]["resources.registration-applications.resource.fetch"];
                    };
                };
            };
            /** @description The signed-in user may not perform this transition on this application. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The transition is not legal from the current status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A reason is required, or the application is incomplete (meta lists what is missing). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
